### ISSUE TITLE
You leaked your token

### ISSUE THREAD

**Issue by Murky-MoMo** [crazyc4t/PatrickStar#1]
https://github.com/Cattodeveloper909/discordjs-bot/blob/f081101577e8acb9f297262c9dc14da42cc6003b/config.json#L4
go to [Developer's portal](https://discord.com/developers/applications) and regenerate it ASAP!

**Comment by crazyc4t** [comment]
Don't worry, Made it with purpose

**Comment by Murky-MoMo** [comment]
Okay then, in case you don't know, anyone can use a token to login to the account that's attached to it and gain control of said account
so I'll assume you know what you're doing and assume that that token in already invalid and close this issue, have a good day :)

**Comment by crazyc4t** [comment]
Have a good day too! I just want to publish it, then change it to document how to change the files including the .json one, but thank you really for the heads up!
